Adding blake3 support
multiformats/go-multihash pull request #158
Opened 2022-06-30 23:21 UTC by laudiacay

Re-exporting blake3 constants in the right places so we can support it elsewhere (like go-verifcid, so that I can add support for approving fixed-length blake3 as a "good hash" there 😄 ) Draft because there are no tests yet.

2022-06-30 23:53 UTC, laudiacay commented
tests passed. I also found a bug in what was being displayed for ErrInconsistentLen and fixed the message to make a little more sense, and added a few comments for clarity... the way the logic was before, it was just gonna print like the same number twice in the "expected `blah` got `bleh`" message no matter what.

2022-06-30 23:54 UTC, laudiacay commented
@Kubuxu @aschmahmann ready 2 go when u r :)

2022-07-01 01:16 UTC, Jorropo requested changes

2022-07-01 02:50 UTC, Jorropo commented
The `ErrInconsistentLen` change looks good to me but I doubt we need to rest.

2022-07-01 02:52 UTC, laudiacay commented
ok i changed the title to fit. i'm gonna leave the new blake3 tests too. committing now.

2022-07-01 02:53 UTC, laudiacay commented on core/registry.go
> +	"lukechampine.com/blake3"
gotcha

2022-07-01 02:58 UTC, Jorropo commented
@laudiacay do the tests passes ?

I think you need to register blake3 in the test suite else they wont find the hasher: simply add this line to your imports (***in the tests***) `_ "github.com/multiformats/go-multihash/register/blake3"`, naming an import `_` (the blank indentifier) will run of it's init functions without adding it's exports to the file scope.

2022-07-01 03:13 UTC, laudiacay commented
register/all gets blake3 and the tests get register/all!

2022-07-01 03:52 UTC, Jorropo commented
Ok good mb

2022-07-01 03:52 UTC, Jorropo approved these changes
SGTM (need green CI first) (I don't have merge powers here)

2022-07-01 07:28 UTC, marten-seemann commented
> Re-exporting blake3 constants in the right places so we can support it elsewhere 

I don't see that anywhere. As far as I can tell, this PR is 1. changing the error messages and 2. adding blake3 tests. Am I missing something?

2022-07-01 13:58 UTC, Jorropo commented
> I don't see that anywhere.

@marten-seemann 

It used to do it but I've asked for it to be removed, I think people that want blake3 can just `import _ "github.com/multiformats/go-multihash/register/blake3"`

2022-07-06 15:23 UTC, laudiacay commented
can we merge?

2022-07-06 15:24 UTC, laudiacay commented
@marten-seemann it's not doing that anymore- it's fixing an error message and adding tests. I was doing that before but then @Jorropo let me know that that was unnecessary :P didn't quite understand go imports with side effects until just now

2022-07-06 15:24 UTC, laudiacay commented
are we good to merge?

2022-07-06 19:43 UTC, laudiacay commented
Yep done

2022-07-26 14:26 UTC, Jorropo approved these changes
LGTM

2022-07-26 14:26 UTC, Jorropo commented on multihash.go
>  type ErrInconsistentLen struct {
Notes for a future PR, IMO, this error should wrap `io.UnexpectedEOF`.

2022-07-26 14:34 UTC, merged